import gql from 'graphql-tag';

export const SAVE_TEMP_STUDENT = gql`
  mutation saveTempStudent($input: TempStudentInput) {
    saveTempStudent(input: $input) {
      cmsTempStudentVo {
        id
        stateMachineId
        studentName
        studentMiddleName
        studentLastName
        fatherName
        fatherMiddleName
        fatherLastName
        motherName
        motherMiddleName
        motherLastName
        studentAadharNo
        studentPanNo
        studentSocialSecurityNo
        studentTaxReferenceNo
        studentBplNo
        studentDrivingLicenseNo
        studentPassportNo
        placeOfBirth
        religion
        caste
        subCaste
        sex
        studentLocalAddress
        studentPermanentAddress
        city
        state
        country
        pinCode
        studentPrimaryCellNumber
        studentAlternateCellNumber
        studentLandLinePhoneNumber
        studentPrimaryEmailId
        studentAlternateEmailId
        relationWithStudent
        emergencyContactName
        emergencyContactMiddleName
        emergencyContactLastName
        emergencyContactCellNumber
        emergencyContactLandLinePhoneNumber
        emergencyContactEmailId
        studentImagePath
        admissionNo
        enrollmentNo
        rollNo
        studentType
        fatherCellNumber
        fatherEmailId
        fatherOccupation
        fatherOfficeEmailId
        fatherOfficeAddress
        fatherOfficeCellNumber
        fatherOfficeLandLinePhoneNumber
        fatherAadharNo
        fatherPanNo
        fatherSocialSecurityNo
        fatherTaxReferenceNo
        fatherBplNo
        fatherDrivingLicenseNo
        fatherPassportNo
        fatherImagePath
        motherCellNumber
        motherEmailId
        motherOccupation
        motherOfficeEmailId
        motherOfficeAddress
        motherOfficeCellNumber
        motherOfficeLandLinePhoneNumber
        motherAadharNo
        motherPanNo
        motherSocialSecurityNo
        motherTaxReferenceNo
        motherBplNo
        motherDrivingLicenseNo
        motherPassportNo
        motherImagePath
        guardianName
        guardianMiddleName
        guardianLastName
        guardianAddress
        guardianCellNumber
        guardianLandLinePhoneNumber
        guardianEmailId
        guardianOccupation
        guardianOfficeEmailId
        guardianOfficeAddress
        guardianOfficeCellNumber
        guardianOfficeLandLinePhoneNumber
        guardianImagePath
        isGuardianSponsorAgency
        sponsorAgencyName
        sponsorAgencyRegistrationNo
        sponsorAgencyAddress
        sponsorAgencyCellNumber
        sponsorAgencyLandLineNumber
        sponsorAgencyEmailId
        sponsorAgencyAppointeeName
        sponsorAgencyAppointeeDesignation
        sponsorAgencyAppointeeCellNumber
        sponsorAgencyAppointeeLandLineNumber
        sponsorAgencyAppointeeEmailId
        sponsorAgencyAppointeeOfficeAddress
        isPhysicallyChallenged
        detailsOfDisability
        disabilityCertificateNo
        disabilityCertificateIssueAuthority
        disabilityCertificateIssueDate
        percentagOfDisability
        bloodGroup
        vaccinationDetails
        otherMedicalDetails
        status
        comments
        departmentId
        branchId
        sectionId
        batchId
        academicYearId
        strDateOfBirth
        strDisabilityCertificateIssueDate
        highestQualification
        yearOfPassing
        lastQualificationPercentage
        lastCollegeAttended
      }
    }
  }
`;
